### PR TITLE
Fix endpoint selector

### PR DESCRIPTION
**Pull request by vxav**
### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Review by glitchcrab — APPROVED** [review]

**Comment by stone-z** [comment]
What's the context for this?

**Comment by stone-z** [comment]
Nvm I see it https://github.com/giantswarm/kyverno-app/blob/main/helm/kyverno/charts/policy-reporter/templates/_helpers.tpl#L37

**Review by stone-z — APPROVED** [review]

**Comment by vxav** [comment]
While testing something else I noticed this mismatch on the CNP.

**Comment by vxav** [comment]
I'll let you release as you see fit

**Pull request merged**
