### PR TITLE
Exclude chart-operator with resourceFilters

### PR DESCRIPTION
**Pull request by fhielpos**
Related issue: https://github.com/giantswarm/giantswarm/issues/27202

### CODE REVIEW

**Comment by fhielpos** [comment]
Tested on `gremlin`, I deleted the pods and also the deployment and it was able to re-create without any exceptions.

**Comment by stone-z** [comment]
Wouldn't policies with auto-gen or those specifically targeting e.g. Deployments still catch chart-operator?

**Comment by fhielpos** [comment]
Yes, just checked and you are right. Will add the deployment too, or would you like to just do any kind in the namespace?

**Comment by fhielpos** [comment]
Added another resource that needs to be excluded.

**Pull request merged**
