### PR TITLE
Add VPA for Kyverno Plugin and enable by default

### PR DESCRIPTION
**Pull request by fhielpos**
Closes https://github.com/giantswarm/giantswarm/issues/26402

### CODE REVIEW

**Comment by fhielpos** [comment]
Does it make sense to bump `kyverno-plugin`?

**Review by stone-z — COMMENTED** [review]
Ok this looks fine technically. I re-ran your test to see if it was just a flake.

I am split about even offering VPA for Kyverno pods. I haven't seen much need to dynamically increase resources yet even in big clusters and I'm sure some well-meaning folks will enable it to downscale for theoretical cost savings, but I can see this turning into a thorn in our side. I'd be inclined to wait until the other Kyverno issues are settled and we have a clearer need for VPA of the Kyverno pods themselves (keeping in mind the pods will totally change with 1.10 anyway). Have you heard any requests for it so far?

On updating the plugin - I expect we'll get that update on the next upstream sync run. I'd keep it separate but we can release the two PRs together.

**Comment by fhielpos** [comment]
Oh sorry, I meant bump the number of replicas as indicated in the issue.

I'm fine without having VPA on Kyverno itself, I think we do have VPA in just one cluster so far. The tests should be fine.

I did not remember about the massive change in 1.10, you are right we will need to rework the controllers then. Should I remove the Kyverno VPA? Or do we keep it until 1.10?

**Comment by stone-z** [comment]
> I meant bump the number of replicas as indicated in the issue.

Oh gotcha. Let's leave it as is for now

> Should I remove the Kyverno VPA? Or do we keep it until 1.10?

I'd drop it personally. If people really want to VPA Kyverno then we can always come back and add it but I'd rather not encourage that right now

**Review by stone-z — APPROVED** [review]

**Pull request merged**
