### PR TITLE
Update CRDS to the same version as the app

### PR DESCRIPTION
**Pull request by jw-s**
### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
Gracias - LGTM

**Comment by MarcelMue** [comment]
CI fails because of permissions AFAICT

**Comment by jw-s** [comment]
> CI fails because of permissions AFAICT

Yeah seems to be looking for the branch in this repo and not the fork.

**Review by stone-z — APPROVED** [review]
LGTM

**Comment by stone-z** [comment]
Tested install + upgrade in WCs and applied it on a test MC. Going to merge + release this

**Pull request merged**
