### PR TITLE
add vpa for kyverno deployment

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
towards https://github.com/giantswarm/giantswarm/issues/27703

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM when tested

**Comment by QuantumEnigmaa** [comment]
Tested and working on `gauss` : 
```bash
zirco@Zirko-laptop:~/kyverno-app$ kg get app kyverno
NAME      INSTALLED VERSION                                  CREATED AT   LAST DEPLOYED   STATUS
kyverno   0.14.10-592a016d605b3d4a58c4643db5b95473fe849506   286d         2m48s           deployed
zirco@Zirko-laptop:~/kyverno-app$ k get vpa -n kyverno
NAME                         MODE   CPU     MEM          PROVIDED   AGE
kyverno-kyverno-plugin-vpa   Auto   15m     104857600    True       69d
kyverno-policyreporter-vpa   Auto   100m    250Mi        True       69d
kyverno-ui-vpa               Auto   15m     50Mi         True       69d
kyverno-vpa                  Auto   3666m   1238659775   True       2m9s
```
Already proved itself useful by stopping kyverno pods from crashlooping

**Comment by QuentinBisson** [comment]
Do you mind testing this in a workload cluster?

**Comment by QuantumEnigmaa** [comment]
> Do you mind testing this in a workload cluster?

Sure no problem

**Comment by stone-z** [comment]
Thanks for taking this on :slightly_smiling_face: we were planning to wait until after the bump to kyverno 1.10 before adding VPA for the admission controllers because of some current implementation details. This work is being done in https://github.com/giantswarm/kyverno-app/pull/269 and we'll come back to this PR after that one is finished (it's has some fairly significant upstream breaking changes)

**Comment by QuantumEnigmaa** [comment]
Ok no problem :)

**Comment by fhielpos** [comment]
We included this in a newer release with the new controller names 😄

**Pull request closed without merging**
