### PR TITLE
Update kyverno 1.7.3

### PR DESCRIPTION
**Pull request by fhielpos**
Towards https://github.com/giantswarm/giantswarm/issues/23700
### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by fhielpos** [comment]
@stone-z what do we need to delete from the CRD job?

**Comment by stone-z** [comment]
> @stone-z what do we need to delete from the CRD job?

These lines https://github.com/giantswarm/kyverno-app/blob/master/helm/kyverno/templates/crd-install/crd-job.yaml#L38-L52
And this RBAC entry: https://github.com/giantswarm/kyverno-app/blob/master/helm/kyverno/templates/crd-install/crd-rbac.yaml#L27

Basically just undoing what was added for CRDs in https://github.com/giantswarm/kyverno-app/pull/151.

**Comment by fhielpos** [comment]
I think thats it 😄

**Comment by stone-z** [comment]
Has this already been tested? Upgrade as well?

**Comment by fhielpos** [comment]
All tested and working ✅  Will wait until you are back in case you want to check anything else

**Comment by fhielpos** [comment]
SELF REMINDER: DON'T SQUASH

**Comment by stone-z** [comment]
Nah I trust you. We'll test this again as part of the whole pack upgrade anyway

**Review by stone-z — APPROVED** [review]
BAM

**Pull request merged**
